# Generated by Django 3.0.6 on 2020-06-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_book', models.CharField(max_length=100, verbose_name='Название книги')),
                ('description_book', models.CharField(max_length=300, verbose_name='описание книги')),
                ('publication_date_book', models.DateTimeField(verbose_name='дата публикации')),
            ],
        ),
    ]
