# Generated by Django 3.0.6 on 2020-06-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_book',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='upload_to = image/'),
        ),
    ]
