# Generated by Django 3.0.6 on 2020-06-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationBook', '0002_book_image_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='description_book',
            field=models.CharField(max_length=1000, verbose_name='описание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_book',
            field=models.FileField(upload_to='image/', verbose_name='ссылки'),
        ),
    ]
